In [1]:
import pandas as pd 

import numpy as np
from numpy import pi


import sklearn
from sklearn import svm

import matplotlib as mpl

import seaborn as sns


In [12]:

a = np.arange(15).reshape(3,5)
print('Size = ',a.size)
a




Size =  15


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2,3))
np.empty((1,2)) # Очень маленькие значения 

array([[0.0e+000, 5.4e-323]])

In [19]:
в = np.arange(10, 30, 5)
в

array([10, 15, 20, 25])

In [22]:
c = np.arange(2)
c

array([0, 1])

In [23]:
rg = np.random.default_rng(1)
b = rg.random((2, 3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

# Создаем данные

In [78]:
np.random.binomial(1,0.5,size = 10).mean()

0.7

In [77]:
np.mean([0, 1, 0, 0, 0, 0, 0, 1, 0, 1])

0.3

In [2]:
n = 1000
result = []
for i in range(n):
    a = np.random.binomial(1,0.03,size = 1000).mean()
    b = np.random.binomial(1,0.05,size = 1000).mean()
    result.append((a,b))

In [3]:
df = pd.DataFrame(result,columns= ['a','b'])


In [6]:
(df.a != df.b).mean()

0.997

In [4]:
df[df['a'] > df['b']]

a      b
4    0.040  0.036
40   0.047  0.041
53   0.050  0.047
78   0.040  0.037
430  0.047  0.039
514  0.043  0.041
648  0.033  0.028
823  0.035  0.031

# PANDAS

In [26]:
anime = pd.read_csv('anime.csv')
rating = pd.read_csv('rating.csv')
anime_modified = anime.set_index('name')

In [27]:
anime

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12294 rows x 7 columns]

In [29]:
df = pd.DataFrame([[1,'Bob', 'Builder'],
                  [2,'Sally', 'Baker'],
                  [3,'Scott', 'Candle Stick Maker']], 
columns=['id','name', 'occupation'])
df

id   name          occupation
0   1    Bob             Builder
1   2  Sally               Baker
2   3  Scott  Candle Stick Maker

In [31]:
anime_copy = anime.copy(deep=True)
anime_copy

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12294 rows x 7 columns]

# Экспорт данных в csv


In [32]:
rating[:10].to_csv('saved_ratings.csv', index=False)

# Просмотр и исследование данных

In [33]:
anime.head(3)
rating.tail(1)

user_id  anime_id  rating
7813736    73516      8074       9

# Подсчёт количества строк в датафрейме

In [34]:
len(df)

3

# Подсчёт количества уникальных значений в столбце

In [36]:
len(rating['user_id'].unique())

73515

# Информация о данных

In [37]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12294 non-null  int64  
 1   name      12294 non-null  object 
 2   genre     12232 non-null  object 
 3   type      12269 non-null  object 
 4   episodes  12294 non-null  object 
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB


In [38]:
anime.describe()

anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [39]:
anime.type.value_counts()

type
TV         3787
OVA        3311
Movie      2348
Special    1676
ONA         659
Music       488
Name: count, dtype: int64

In [42]:
anime['genre'].tolist()
# anime['genre']

['Drama, Romance, School, Supernatural',
 'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Sci-Fi, Thriller',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Comedy, Drama, School, Shounen, Sports',
 'Action, Adventure, Shounen, Super Power',
 'Drama, Military, Sci-Fi, Space',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Drama, Fantasy, Romance, Slice of Life, Supernatural',
 'Drama, School, Shounen',
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
 'Action, Drama, Mecha, Military, Sci-Fi, Super Power',
 'Comedy, Drama, School, Shounen, Sports',
 'Adventure, Drama, Supernatural',
 'Drama, Music, Romance, School, Shounen',
 'Adventure, Fantasy, Historical, Mystery, Seinen, Slice of Life, Supernatural',
 'Fantasy, Slice of Life',
 'Action, Mecha, Military, School, Sci-Fi, Super Power',
 

In [43]:
anime_modified.index.tolist()

['Kimi no Na wa.',
 'Fullmetal Alchemist: Brotherhood',
 'Gintama°',
 'Steins;Gate',
 'Gintama&#039;',
 'Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou',
 'Hunter x Hunter (2011)',
 'Ginga Eiyuu Densetsu',
 'Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare',
 'Gintama&#039;: Enchousen',
 'Clannad: After Story',
 'Koe no Katachi',
 'Gintama',
 'Code Geass: Hangyaku no Lelouch R2',
 'Haikyuu!! Second Season',
 'Sen to Chihiro no Kamikakushi',
 'Shigatsu wa Kimi no Uso',
 'Mushishi Zoku Shou 2nd Season',
 'Ookami Kodomo no Ame to Yuki',
 'Code Geass: Hangyaku no Lelouch',
 'Hajime no Ippo',
 'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen',
 'Cowboy Bebop',
 'One Punch Man',
 'Mononoke Hime',
 'Suzumiya Haruhi no Shoushitsu',
 'Monogatari Series: Second Season',
 'Mushishi Zoku Shou',
 'Mushishi',
 'Tengen Toppa Gurren Lagann',
 'Great Teacher Onizuka',
 'Natsume Yuujinchou Go',
 'Hajime no Ippo: New Challenger',
 'Mushishi Zoku Shou: Suzu no Shizuku',
 'Natsume Yuuji

In [44]:
anime.columns.tolist()

['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members']

# Добавление данных в датафрейм и удаление их из него

In [45]:
anime['train set'] = True

# Создание нового датафрейма из подмножества столбцов

In [46]:
anime[['name','episodes']]

name episodes
0                                         Kimi no Na wa.        1
1                       Fullmetal Alchemist: Brotherhood       64
2                                               Gintama°       51
3                                            Steins;Gate       24
4                                          Gintama&#039;       51
...                                                  ...      ...
12289       Toushindai My Lover: Minami tai Mecha-Minami        1
12290                                        Under World        1
12291                     Violence Gekiga David no Hoshi        4
12292  Violence Gekiga Shin David no Hoshi: Inma Dens...        1
12293                   Yasuji no Pornorama: Yacchimae!!        1

[12294 rows x 2 columns]

# Удаление заданных столбцов


In [47]:
anime.drop(['anime_id', 'genre', 'members'], axis=1).head()

name   type episodes  rating  train set
0                    Kimi no Na wa.  Movie        1    9.37       True
1  Fullmetal Alchemist: Brotherhood     TV       64    9.26       True
2                          Gintama°     TV       51    9.25       True
3                       Steins;Gate     TV       24    9.17       True
4                     Gintama&#039;     TV       51    9.16       True

In [51]:
df = pd.DataFrame([[1,'Bob', 8000],
                  [2,'Sally', 9000],
                  [3,'Scott', 20]], columns=['id','name', 'power level'])
df
df.append(df.sum(axis=0), ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

# 7. Комбинирование датафреймов

In [52]:
df1 = anime[0:2]
df2 = anime[2:4]
pd.concat([df1, df2], ignore_index=True)

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   

   members  train set  
0   200630       True  
1   793665       True  
2   114262       True  
3   673572       True

In [54]:
rating.merge(anime, left_on='anime_id', right_on='anime_id', suffixes=('_left', '_right'))

user_id  anime_id  rating_left  \
0              1        20           -1   
1              3        20            8   
2              5        20            6   
3              6        20           -1   
4             10        20           -1   
...          ...       ...          ...   
7813722    65682     30450            8   
7813723    69497     33484           10   
7813724    70463     29481           -1   
7813725    72404     34412           -1   
7813726    72800     30738            4   

                                                      name  \
0                                                   Naruto   
1                                                   Naruto   
2                                                   Naruto   
3                                                   Naruto   
4                                                   Naruto   
...                                                    ...   
7813722  Dr. Slump: Hoyoyo! Arale no Himitsu Dai Koukai...   
7813723                                         Shiroi Zou   
7813724                                    Kakinoki Mokkii   
7813725                 Hashiri Hajimeta bakari no Kimi ni   
7813726                       Gamba: Gamba to Nakama-tachi   

                                                     genre     type episodes  \
0        Action, Comedy, Martial Arts, Shounen, Super P...       TV      220   
1        Action, Comedy, Martial Arts, Shounen, Super P...       TV      220   
2        Action, Comedy, Martial Arts, Shounen, Super P...       TV      220   
3        Action, Comedy, Martial Arts, Shounen, Super P...       TV      220   
4        Action, Comedy, Martial Arts, Shounen, Super P...       TV      220   
...                                                    ...      ...      ...   
7813722                            Comedy, Sci-Fi, Shounen  Special        1   
7813723                           Action, Historical, Kids    Movie        1   
7813724                                      Fantasy, Kids  Special        1   
7813725                                              Music    Music        1   
7813726                                    Adventure, Kids    Movie        1   

         rating_right  members  train set  
0                7.81   683297       True  
1                7.81   683297       True  
2                7.81   683297       True  
3                7.81   683297       True  
4                7.81   683297       True  
...               ...      ...        ...  
7813722          6.17      248       True  
7813723          4.71       45       True  
7813724          4.33       61       True  
7813725          6.76      239       True  
7813726          5.55      185       True  

[7813727 rows x 10 columns]

# Фильтрация 

In [55]:
anime_modified.loc[['Haikyuu!! Second Season','Gintama']]

anime_id  \
name                                
Haikyuu!! Second Season     28891   
Gintama                       918   

                                                                     genre  \
name                                                                         
Haikyuu!! Second Season             Comedy, Drama, School, Shounen, Sports   
Gintama                  Action, Comedy, Historical, Parody, Samurai, S...   

                        type episodes  rating  members  
name                                                    
Haikyuu!! Second Season   TV       25    8.93   179342  
Gintama                   TV      201    9.04   336376

# Получение строк по числовым индексам

In [56]:
anime_modified.iloc[0:3]

anime_id  \
name                                         
Kimi no Na wa.                       32281   
Fullmetal Alchemist: Brotherhood      5114   
Gintama°                             28977   

                                                                              genre  \
name                                                                                  
Kimi no Na wa.                                 Drama, Romance, School, Supernatural   
Fullmetal Alchemist: Brotherhood  Action, Adventure, Drama, Fantasy, Magic, Mili...   
Gintama°                          Action, Comedy, Historical, Parody, Samurai, S...   

                                   type episodes  rating  members  
name                                                               
Kimi no Na wa.                    Movie        1    9.37   200630  
Fullmetal Alchemist: Brotherhood     TV       64    9.26   793665  
Gintama°                             TV       51    9.25   114262

In [57]:
anime[anime['type'].isin(['TV', 'Movie'])]

anime_id                              name  \
0         32281                    Kimi no Na wa.   
1          5114  Fullmetal Alchemist: Brotherhood   
2         28977                          Gintama°   
3          9253                       Steins;Gate   
4          9969                     Gintama&#039;   
...         ...                               ...   
11738      3038           Senya Ichiya Monogatari   
11805      2755                         Cleopatra   
12244     11141                      Blue Seagull   
12258     20007     Hi Gekiga Ukiyoe Senya Ichiya   
12293     26081  Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
11738                                    Fantasy, Hentai  Movie        1   
11805                                 Hentai, Historical  Movie        1   
12244                                     Action, Hentai  Movie        1   
12258                                     Action, Hentai  Movie        1   
12293                                             Hentai  Movie        1   

       rating  members  train set  
0        9.37   200630       True  
1        9.26   793665       True  
2        9.25   114262       True  
3        9.17   673572       True  
4        9.16   151266       True  
...       ...      ...        ...  
11738    6.18     1394       True  
11805    6.06     1709       True  
12244    4.60      337       True  
12258    1.92      129       True  
12293    5.46      142       True  

[6135 rows x 8 columns]

In [64]:
anime[(anime['type'] == 'TV') | (anime['type'] ==  'Movie')]

anime_id                              name  \
0         32281                    Kimi no Na wa.   
1          5114  Fullmetal Alchemist: Brotherhood   
2         28977                          Gintama°   
3          9253                       Steins;Gate   
4          9969                     Gintama&#039;   
...         ...                               ...   
11738      3038           Senya Ichiya Monogatari   
11805      2755                         Cleopatra   
12244     11141                      Blue Seagull   
12258     20007     Hi Gekiga Ukiyoe Senya Ichiya   
12293     26081  Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
11738                                    Fantasy, Hentai  Movie        1   
11805                                 Hentai, Historical  Movie        1   
12244                                     Action, Hentai  Movie        1   
12258                                     Action, Hentai  Movie        1   
12293                                             Hentai  Movie        1   

       rating  members  train set  
0        9.37   200630       True  
1        9.26   793665       True  
2        9.25   114262       True  
3        9.17   673572       True  
4        9.16   151266       True  
...       ...      ...        ...  
11738    6.18     1394       True  
11805    6.06     1709       True  
12244    4.60      337       True  
12258    1.92      129       True  
12293    5.46      142       True  

[6135 rows x 8 columns]

# Срез


In [65]:
anime[1:3]

anime_id                              name  \
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   

                                               genre type episodes  rating  \
1  Action, Adventure, Drama, Fantasy, Magic, Mili...   TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...   TV       51    9.25   

   members  train set  
1   793665       True  
2   114262       True

# Фильтрация по значению

In [66]:
anime[anime['rating'] > 8]

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
10765     32230                                          Xi You Ji   
10786     26313                    Yakusoku: Africa Mizu to Midori   
10793     28557  Yamete! Writer Asobi: Doubutsu Mura no Shoubou...   
10847     26097                                    Yume no Tsuzuki   
12251     33960  Chou Do M na Hentai Mesu-tachi Otokoton Chouky...   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
10765                                 Adventure, Fantasy     TV       52   
10786                                        Drama, Kids    OVA        1   
10793                                        Drama, Kids    OVA        1   
10847                                        Drama, Kids    OVA        1   
12251                                             Hentai    OVA  Unknown   

       rating  members  train set  
0        9.37   200630       True  
1        9.26   793665       True  
2        9.25   114262       True  
3        9.17   673572       True  
4        9.16   151266       True  
...       ...      ...        ...  
10765    8.07       89       True  
10786    9.25       53       True  
10793    8.67       40       True  
10847    8.67       53       True  
12251    8.38      161       True  

[583 rows x 8 columns]

# Сортировка

In [67]:
anime.sort_values('rating', ascending=False)

anime_id                                               name  \
10464     33662            Taka no Tsume 8: Yoshida-kun no X-Files   
10400     30120                        Spoon-hime no Swing Kitchen   
9595      23005                                   Mogura no Motoro   
0         32281                                     Kimi no Na wa.   
9078      33607                                       Kahei no Umi   
...         ...                                                ...   
12274     34492  Nuki Doki! Tenshi to Akuma no Sakusei Battle -...   
12279     34491                       Sagurare Otome The Animation   
12280     34312                                       Saimin Class   
12282     34388                    Shikkoku no Shaga The Animation   
12285     34399                                   Taimanin Asagi 3   

                                      genre   type episodes  rating  members  \
10464                        Comedy, Parody  Movie        1   10.00       13   
10400                       Adventure, Kids     TV  Unknown    9.60       47   
9595                          Slice of Life  Movie        1    9.50       62   
0      Drama, Romance, School, Supernatural  Movie        1    9.37   200630   
9078                             Historical  Movie        1    9.33       44   
...                                     ...    ...      ...     ...      ...   
12274                                Hentai    OVA  Unknown     NaN      392   
12279                                Hentai    OVA        1     NaN       79   
12280                                Hentai    OVA  Unknown     NaN      240   
12282                                Hentai    OVA  Unknown     NaN      195   
12285          Demons, Hentai, Supernatural    OVA  Unknown     NaN      485   

       train set  
10464       True  
10400       True  
9595        True  
0           True  
9078        True  
...          ...  
12274       True  
12279       True  
12280       True  
12282       True  
12285       True  

[12294 rows x 8 columns]

In [68]:
anime.groupby('type').count()

anime_id  name  genre  episodes  rating  members  train set
type                                                                
Movie        2348  2348   2306      2348    2297     2348       2348
Music         488   488    488       488     488      488        488
ONA           659   659    655       659     652      659        659
OVA          3311  3311   3310      3311    3285     3311       3311
Special      1676  1676   1674      1676    1671     1676       1676
TV           3787  3787   3777      3787    3671     3787       3787

In [69]:
anime.groupby(["type"]).agg({
  "rating": "sum",
  "episodes": "count",
  "name": "last"
}).reset_index()

type    rating  episodes  \
0    Movie  14512.58      2348   
1    Music   2727.43       488   
2      ONA   3679.43       659   
3      OVA  20942.60      3311   
4  Special  10900.77      1676   
5       TV  25338.34      3787   

                                                name  
0                   Yasuji no Pornorama: Yacchimae!!  
1                                       Yuu no Mahou  
2                                     Docchi mo Maid  
3  Violence Gekiga Shin David no Hoshi: Inma Dens...  
4                   Junjou Shoujo Et Cetera Specials  
5       Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou

In [70]:
tmp_df = rating.copy()
tmp_df.sort_values('user_id', ascending=True, inplace=True)
tmp_df = tmp_df[tmp_df.user_id < 10] 
tmp_df = tmp_df[tmp_df.anime_id < 30]
tmp_df = tmp_df[tmp_df.rating != -1]
pd.pivot_table(tmp_df, values='rating', index=['user_id'], columns=['anime_id'], aggfunc=np.sum, fill_value=0)


C:\Users\Katarsis\AppData\Local\Temp\ipykernel_18980\4098679756.py:6: FutureWarning: The provided callable <function sum at 0x0000029C3F5F1EE0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.pivot_table(tmp_df, values='rating', index=['user_id'], columns=['anime_id'], aggfunc=np.sum, fill_value=0)


anime_id  6   15  17  18  20  22  24
user_id                             
3          0   0   0   0   8   0   0
5          8   6   6   6   6   5   1
7          0   0   0   0   0   7   0

In [71]:
pivot = pd.pivot_table(tmp_df, values='rating', index=['user_id'], columns=['anime_id'], aggfunc=np.sum)
pivot.fillna(0)

C:\Users\Katarsis\AppData\Local\Temp\ipykernel_18980\2996192501.py:1: FutureWarning: The provided callable <function sum at 0x0000029C3F5F1EE0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot = pd.pivot_table(tmp_df, values='rating', index=['user_id'], columns=['anime_id'], aggfunc=np.sum)


anime_id   6    15   17   18   20   22   24
user_id                                    
3         0.0  0.0  0.0  0.0  8.0  0.0  0.0
5         8.0  6.0  6.0  6.0  6.0  5.0  1.0
7         0.0  0.0  0.0  0.0  0.0  7.0  0.0

In [72]:
anime.sample(frac=0.25)

anime_id                                         name  \
6641       4210                   Gokiburi-tachi no Tasogare   
1550      21435                 Yama no Susume Second Season   
7430       6318                               Kigurumikku V3   
4933       9857  Bakusou Kyoudai Let&#039;s &amp; Go Special   
3992      10823                 Ranma ½: 1994 Music Calendar   
...         ...                                          ...   
7033      20713                                      Mai Zhu   
8579      29179                   Futago no Ookami Daibouken   
3657       4074                 Kouya no Yobigoe: Hoero Buck   
10735     12005                         What&#039;s Michael?   
9660      19797          Nanbo no Monjai! 2: Yankee Gurentai   

                                     genre     type episodes  rating  members  \
6641                       Drama, Military    Movie        1    6.02      794   
1550      Adventure, Comedy, Slice of Life       TV       24    7.51    11413   
7430   Comedy, Ecchi, Magic, Mecha, Parody      ONA        3    5.44     1181   
4933      Adventure, Cars, Shounen, Sports  Special        1    6.59      344   
3992   Comedy, Martial Arts, Slice of Life      OVA        1    6.83     1730   
...                                    ...      ...      ...     ...      ...   
7033                    Comedy, Historical    Movie        1    5.78      180   
8579                           Kids, Music    Music        1    4.20       85   
3657                      Adventure, Drama  Special        1    6.92      650   
10735                               Comedy      OVA        1    5.71      173   
9660                        Action, Comedy      OVA        1    5.00       56   

       train set  
6641        True  
1550        True  
7430        True  
4933        True  
3992        True  
...          ...  
7033        True  
8579        True  
3657        True  
10735       True  
9660        True  

[3074 rows x 8 columns]

In [73]:
for idx,row in anime[:2].iterrows():
    print(idx, row)

0 anime_id                                    32281
name                               Kimi no Na wa.
genre        Drama, Romance, School, Supernatural
type                                        Movie
episodes                                        1
rating                                       9.37
members                                    200630
train set                                    True
Name: 0, dtype: object
1 anime_id                                                  5114
name                          Fullmetal Alchemist: Brotherhood
genre        Action, Adventure, Drama, Fantasy, Magic, Mili...
type                                                        TV
episodes                                                    64
rating                                                    9.26
members                                                 793665
train set                                                 True
Name: 1, dtype: object
